### ISSUE TITLE
PR-based workflow implementation

### ISSUE THREAD

**Issue by tnikic** [tnikic/skills#54]
## Problem Statement

The current ticket pipeline lets `implement` push completed work directly to `main` and close the ticket before CI has validated the resulting commit. A later CI failure can therefore leave the tracker reporting completed work while `main` is broken. The workflow also lacks a consistent handoff from agent execution to human review, a reliable definition of readiness, and a safe way to process review feedback on open pull requests.

## Solution

Move delivery from direct pushes to a PR-based workflow. `implement` will work on a Conventional Branch, run the local quality and pre-PR review gates, push the branch, and open a PR whose body projects the ticket. Forge-required CI for the exact PR head will be the authoritative merge gate. The agent will stop at ready-for-review, while a human reviews and squash-merges the PR. The linked ticket will close only when the PR merges.

The workflow will also provide impact labels for review triage, dedicated repair for stale or conflicting branches, and a `review-analysis` skill that interprets PR comments while respecting the identity boundary between trusted operators and external commenters. Forge-specific operations remain behind the `github` and `gitlab` skills, while the workflow consumes normalized outcomes.

## User Stories

1. As an agent implementing a ticket, I want to work on a feature branch, so that incomplete or broken work cannot be pushed directly to `main`.
2. As an agent implementing a ticket, I want the branch name to identify its purpose, ticket, and spec, so that a branch can be traced back to the work it carries.
3. As a maintainer, I want one branch naming convention across GitHub and GitLab, so that the workflow does not fork by forge.
4. As an agent, I want `implement` to own the transition from completed work to an open PR, so that there is one clear handoff owner.
5. As a maintainer, I want `commit` to remain the universal local commit-quality gate, so that PR creation does not bypass local safety, quality, or documentation checks.
6. As a contributor, I want commit messages to remain free of forge-specific issue-closing metadata, so that commit history remains reusable across branches and forges.
7. As a reviewer, I want the PR body to project the ticket's purpose, changes, and acceptance criteria, so that I can review the intended work without reconstructing it from commits.
8. As a maintainer, I want the PR to contain a `Closes #N` relationship to the ticket, so that the ticket closes automatically only after the PR reaches `main`.
9. As an agent, I want one PR per ticket by default, so that each unit of work has an independently reviewable delivery boundary.
10. As a spec author, I want to opt into a combined PR when several tickets must share one branch, so that the workflow can support intentionally unified delivery without making it the default.
11. As a maintainer, I want stacked PRs to use native forge stack behavior, so that branch retargeting and merge ordering are handled by the forge rather than reimplemented in the skills.
12. As a reviewer, I want PR titles to group work by spec and show provisional merge position, so that parallel work remains legible in the PR list.
13. As a human reviewer, I want the agent to run project `check` before opening a PR, so that obvious local quality failures are caught before handoff.
14. As a human reviewer, I want `implement` to run Standards and Spec review against the branch merge-base, so that the agent's implementation is checked against both repository conventions and the originating ticket or spec.
15. As a maintainer, I want Coverage review to remain owned by `improve-codebase-architecture`, so that normal implementation does not duplicate architectural coverage analysis.
16. As an agent, I want clear pre-PR findings fixed automatically, so that routine quality issues do not require human intervention.
17. As a human, I want judgment-dependent findings surfaced before PR creation, so that the agent does not make unapproved architectural or semantic decisions.
18. As a maintainer, I want the documentation gate to run before a PR is opened or updated, so that the PR does not hand off stale human-facing documentation.
19. As a project maintainer, I want CI to run both the project `check` and `test` targets on every PR head, so that the merge gate validates the full project quality contract.
20. As a maintainer, I want the required status to bind to the exact current PR head, so that an older green commit cannot authorize a newer untested commit.
21. As an agent, I want to wait for all forge-required checks after opening or updating a PR, so that I do not declare work ready while required validation is pending.
22. As a maintainer, I want optional checks to remain informational, so that readiness is determined by declared protection rules rather than incidental jobs.
23. As a maintainer, I want a missing required-check configuration reported as a repository gap, so that the agent never treats absent protection as permission to proceed.
24. As an agent, I want a bounded wait window for CI, so that a hung or unavailable pipeline leaves the PR open and not-ready instead of blocking indefinitely.
25. As an agent, I want deterministic, ticket-scoped branch failures to be auto-fixed for at most two cycles, so that obvious failures can recover without an unbounded repair loop.
26. As a human, I want infrastructure, flaky, ambiguous, unrelated, and scope-expanding failures handed to me with evidence, so that the agent does not guess at repairs.
27. As a human reviewer, I want failed required-job logs summarized rather than copied wholesale into the tracker, so that the failure record is useful without becoming noisy.
28. As a human reviewer, I want the agent to stop at ready-for-review, so that no agent or forge automation can merge code without human approval.
29. As a human reviewer, I want every merge to be a squash merge, so that each PR contributes one clean commit to `main`.
30. As a maintainer, I want the branch current with `main` before merge, so that the reviewed code is the code that CI validates and the merge does not discover avoidable conflicts.
31. As a maintainer, I want the ticket to remain open and assigned through implementation and review, so that tracker state represents delivered work rather than claimed work.
32. As a human reviewer, I want a ready PR assigned to me for review, so that ownership transfers visibly at the handoff boundary.
33. As a maintainer, I want a merged PR to close its linked ticket automatically, so that completion is recorded at delivery time.
34. As a human operator, I want clear trusted review instructions to trigger the appropriate follow-up, so that review comments can drive implementation, rejection, or a new ticket without manual translation.
35. As a human operator, I want ambiguous trusted review comments to start one clarification session per PR, so that the agent acts only after intent is clear.
36. As a maintainer, I want external review comments summarized but not executed, so that untrusted forge participants cannot trigger code changes or lifecycle operations.
37. As a reviewer, I want the skill's reply comment to mark a comment batch as processed, so that review history and auditability live in the tracker.
38. As a human, I want review comments for one PR batched into a proposed action summary, so that I can approve a coherent response rather than answer the same review cycle piecemeal.
39. As an agent responding to approved feedback, I want `review-analysis` to reuse `implement` on the existing branch, so that feedback follows the same edit, test, documentation, review, push, and CI gates as initial work.
40. As a maintainer, I want merge conflicts surfaced during feedback updates to go through merge-conflict repair, so that review response and branch maintenance remain separate responsibilities.
41. As a maintainer, I want stale or conflicting open PRs detected after every merge, so that remaining work does not silently become unmergeable.
42. As a maintainer, I want conflict repair performed in an isolated worktree, so that repairing one branch cannot corrupt another agent's workspace.
43. As an agent performing conflict repair, I want to rebase onto the current base and rerun checks and CI, so that the repaired branch is validated against the code it will merge with.
44. As a human, I want semantic or unclear conflicts handed to me, so that repair never changes behavior without an explicit decision.
45. As a reviewer, I want PRs labeled by impact as critical, high, normal, or low, so that I can order review attention by security risk, blast radius, and change breadth.
46. As a spec author, I want each ticket's impact declared in the spec, so that review triage is intentional rather than inferred late.
47. As an agent, I want `implement` to apply the declared impact label when opening the PR, so that the PR list is immediately sortable.
48. As a maintainer, I want undeclared impact to default to normal, so that every PR has a predictable triage value.
49. As a human reviewer, I want impact to remain advisory rather than merge-gating, so that no label value can replace human approval or CI.
50. As a maintainer, I want the workflow history to remain in issues, PRs, and comments, so that implementation decisions and review actions are discoverable without parallel spec artifacts.

## Implementation Decisions

- `implement` owns PR creation after implementation is complete. It claims the ticket, performs the work, runs the required gates, pushes the branch, opens the PR, posts the handoff summary, assigns the ticket to the human, requests review, and leaves both PR and ticket open.
- `commit` remains the universal commit gate for local safety, project quality, and documentation checks. PR creation extends the delivery workflow but does not replace or bypass the commit gate.
- The PR body is generated from a shared PR template and contains the change summary, resulting changes, acceptance criteria mirrored from the ticket, and a `Closes #N` footer. Issue closure metadata belongs in the PR body, not in the commit message.
- Per-ticket PRs are the default. A spec may declare one combined PR; the combined branch uses the spec slug without a ticket number and accepts incremental pushes until the single PR merges.
- Agent branches follow the forge-independent Conventional Branch convention. Per-ticket branches contain the mapped purpose prefix, ticket number, and spec slug. Combined branches contain the purpose prefix and spec slug. Merge-order numbers never appear in branch names.
- Branch purpose is mapped from the dominant ticket commit type, with `chore` as fallback and the documented `refactor` extension available to the team. The forge deletes the remote branch after merge, and the agent removes local branch/worktree state after completion.
- PR titles use the spec slug and provisional merge position in the form established by the map. The fleet manager may normalize those positions after parallel work settles; this orchestration is not part of `implement`.
- Native forge stack behavior is used for stacked PRs and retargeting. GitHub and GitLab differences remain in their forge skills rather than in shared workflow logic.
- The pre-PR sequence is: project `check`, Standards and Spec review against the branch merge-base and originating ticket/spec, correction of clear findings, human escalation for judgment calls, project `check` again, full project `test`, documentation gate, branch push, PR creation, and CI readiness wait.
- `code-review` is an internal pre-PR gate owned by `implement`, not a CI job or merge gate. Only Standards and Spec axes run in this workflow. Coverage remains the responsibility of `improve-codebase-architecture`.
- The shared command runner abstracts whether the project uses `make` or `just`; workflow logic must consume target names rather than hard-code one runner.
- CI is the authoritative merge gate. It runs the project's `check` and `test` targets on every PR head, with build and end-to-end coverage where the project profile requires them. Local pre-commit checks remain fast feedback.
- Forge skills expose exact provider-specific status queries. `implement` consumes normalized outcomes: pending, success, failure, cancelled, and stale.
- Readiness requires every check required by branch protection or forge rulesets to pass for the exact current PR head. Optional checks do not authorize or block readiness. Missing required protection is reported as a repository configuration gap.
- The CI wait window is configurable and defaults to 30 minutes. A timeout leaves the PR open and explicitly not ready for review.
- Automatic failure repair is limited to deterministic, branch-caused failures covered by the ticket, for no more than two cycles. Infrastructure, flaky, ambiguous, unrelated, or scope-expanding failures are summarized for the human with relevant logs and status evidence.
- The human is the only merger. The branch must be current with `main`, CI must be green for that current head, and the human performs a squash merge. No agent merge and no forge auto-merge are part of this workflow.
- A linked ticket remains open and assigned through review. The PR's `Closes #N` relationship closes it only at merge. A rejected change is handled from a trusted review instruction through `review-analysis`; a PR closed without merge is not given an automatic cleanup or reopening behavior.
- `review-analysis` supports explicit PR invocation and self-discovery of open PRs with unaddressed comments. It batches comments per PR, classifies each commenter using forge identity, and replies in the PR thread as both response and processed marker.
- Clear instructions from trusted operators may trigger direct action, including invoking `implement`, creating a follow-up ticket, or handling an intentional rejection. Ambiguous trusted instructions require one grilling pass before action. External comments are analyzed and summarized only; they never trigger action without explicit human instruction.
- `review-analysis` orchestrates but does not implement. Approved feedback reuses `implement` on the existing branch. Merge conflicts discovered during that work go to the dedicated merge-conflict-repair workflow.
- The fleet manager detects stale or conflicting PRs after each merge and dispatches merge-conflict repair in an isolated worktree. Repair rebases onto the current base and reruns checks and CI. Only clear mechanical conflicts covered by the ticket are repaired automatically; semantic conflicts stop for human input. Repair does not reopen or reassign the ticket.
- The PR impact scope has values critical, high, normal, and low, with normal as the default. Critical is reserved for security, authentication, and high-blast-radius changes; high covers broad or important changes; low covers trivial changes.
- Specs declare impact per ticket, and `implement` applies the corresponding label to the PR at open. Impact is review triage only and never gates CI, readiness, or merge.
- Forge operations continue to route through the `github` and `gitlab` skills. The workflow owns interpretation and sequencing; provider-specific commands remain documented in the forge adapters.
- ADRs and the domain context remain the durable repository documentation for architectural decisions and vocabulary. Routine review and implementation history remains in the issue tracker rather than in new parallel spec documents.

## Testing Decisions

- Tests will verify externally observable workflow behavior through the highest existing seam: the skill-to-forge interaction and the shared command-runner contract. They should assert branch, PR, ticket, label, readiness, and comment outcomes rather than internal helper calls or prompt wording.
- The `implement` workflow will be tested for the complete handoff: local gates run in the required order, the correct branch is pushed, the PR body projects the ticket, impact is applied, CI status is awaited for the current head, and the ticket remains open until merge.
- PR creation tests will cover default per-ticket delivery, combined-spec opt-in, branch naming, PR title numbering, acceptance-criteria projection, and `Closes #N` placement.
- CI status tests will cover pending, success, failure, cancelled, stale, timeout, missing required protection, optional checks, newer-head invalidation, bounded auto-fix, and human escalation. GitHub and GitLab command differences should be tested at their forge adapter seams, while normalized outcomes are tested once in shared workflow behavior.
- Lifecycle tests will cover assignment transfer at ready-for-review, no agent or auto merge, squash-only human merge expectations, and closure only after merge.
- Review-analysis tests will cover explicit and discovery invocation, batching, trusted clear intent, trusted ambiguity, external comments, reply markers, implement delegation, and preservation of tracker history.
- Merge-conflict repair tests will cover post-merge detection, isolated repair, rebase rather than merge-base integration, check and CI reruns, mechanical repair, semantic escalation, and unchanged ticket state.
- Impact-label tests will cover all four values, normal defaulting, application at PR open, and the absence of any merge-gating behavior.
- Existing repository prior art is the `check` target's gitleaks, offline link, and label-taxonomy checks, along with the shared command-runner target names. Those checks remain the local and CI quality foundation; the new workflow tests should invoke them through their public targets rather than duplicate their implementation.
- The project currently declares `check` but not a full `test` target. Implementation must add or align the executable test target and CI pipeline as part of the project profile before relying on it as an authoritative merge gate.
- Tests must follow feedback-first TDD: establish a smallest provable vertical check through the real forge/workflow seam before adding edge cases, then finish with the full project test target and the PR-head CI path.

## Out of Scope

- The fleet manager's complete orchestration design, including concurrency policy, worktree scheduling, stack ordering, title renumbering after parallel runs, and post-merge coordination as a standalone capability. That work belongs to the follow-up map identified by the source map.
- Implementing the actual PR-based workflow in this spec issue. This issue defines the route for subsequent ticketing and implementation.
- Forge-specific reimplementation of native stack mechanics, merge queues, branch protection, or pipeline engines.
- Agent-controlled merges, forge auto-merge, or automatic approval of human review.
- Background polling after a human merge.
- Automatic handling of closed-but-unmerged PRs as a built-in cleanup sweep.
- Acting on external review comments without explicit human instruction.
- A new status label for ready-for-review or a reinterpretation of `triage:for-human`.
- Making impact labels a priority system or a merge gate.
- Broad coverage analysis as part of every `implement` run; Coverage remains with `improve-codebase-architecture`.
- Changing project behavior unrelated to the PR delivery workflow.

## Further Notes

- The source map is closed with all ten decision tickets resolved. Its residual fog is the fleet-manager workflow, which is intentionally preserved as a separate follow-up map rather than folded into this spec.
- The repository's existing ADRs establish the key constraints: `implement` owns PR creation, CI is the merge gate, merges are human-controlled squash merges, tickets close at merge, code review is pre-PR, CI results bind to the PR head, merge-conflict repair is dedicated, and review comments have an identity boundary.
- The spec should be decomposed into agent-sized tickets in dependency order. Foundational shared contracts and forge status normalization should precede the `implement` handoff, lifecycle, review-analysis, and repair workflows.
- Every resulting ticket should declare its review impact so `implement` can stamp the PR consistently.

**Comment by tnikic** [comment]
All sub-issues are closed and the PR-based workflow spec is complete.
